version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - prometheusTSDB:/prometheus
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:9.4.7-ubuntu
    container_name: grafana
    volumes:
      - grafanaDb:/var/lib/grafana
    ports:
      - 3000:3000
  
  server:
    build: .
    container_name: server
    ports:
      - 4000:4000
    tty: true

volumes:
  # Sqlite by default
  grafanaDb:
  # Prometheus' own timeseries db.
  prometheusTSDB: